# Generated by Django 3.0.5 on 2020-04-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20200418_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
