# Generated by Django 3.0.5 on 2020-04-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20200418_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
