# Generated by Django 3.0.5 on 2020-10-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='price_per_item',
            field=models.IntegerField(default=0),
        ),
    ]
