# Generated by Django 3.0.5 on 2020-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20201005_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
