# Generated by Django 3.0.5 on 2020-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_auto_20201005_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
