# Generated by Django 3.0.5 on 2020-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_auto_20200501_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
